### ISSUE TITLE
Spigot 1.8.8 don't work

### ISSUE THREAD

**Issue by GabrielMax-1** [LuckPerms/LuckPerms#3194]
### Description

Hello LuckPerms programmers, I want to report something that happened to me: when I go to install the luckperms plugin from its official page in the 1.8 Spigot / Bukkit / Paper option, when I turn on the server, the plugin does not run (let's clarify that I have spigot 1.8 .8) please solve, I like to use that plugin but it only runs in minecraft 1.16 :(, I ask you to comment on the version for that server, since, no permission plugin like permex or groupmananger has as many options as its plugin.
Thank you

### Reproduction Steps

.

### Expected Behaviour

.

### Server Details

Spigot:1.8.8

### LuckPerms Version

v5.3.74

**Comment by Laarryy** [comment]
If you would like support, you need to please include logs, as well as the other required fields. Please re-open a new issue and provide all of the requested, pertinent information, otherwise we cannot help you. Furthermore, if you simply need support with getting LuckPerms running, please click the provided discord link (https://discord.gg/luckperms) and we're happy to help troubleshoot in real-time over there. Thanks!
