### ISSUE TITLE
New Remote Storage type | Couchbase

### ISSUE THREAD

**Issue by Nisutec** [LuckPerms/LuckPerms#3205]
### Description

Please add Couchbase as a Remote Storage type for LuckPerms.

### Proposed Behaviour

Couchbase is a very performance and scalable NOSQL Database. It uses a SQL-friendly query language for JSON Data.

**Comment by Laarryy** [comment]
Considering the wealth of other options available, there doesn't seem to be a great reason to add this alternative database option. If there are any others that would like to see this added, feel free to react to this message with a 👍 and we can revisit at a later date. 
However, considering that your suggestion is not only the first time this storage method has been requested, it is also the first time that anyone on the LP team has heard of its existence, it seems a highly esoteric addition with added maintenance cost and little user benefit. 
Since it is so simple to set up a regular old MySQL or MariaDB database, connect it to LP, and forget about it, and since there is little to no performance concern in how LP uses databases, it doesn't seem to make sense to add yet another 'performance centered' or scalable solution. Especially since there are already so many *more than adequate* solutions.
