### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by xR4Z3R** [LuckPerms/LuckPerms#3207]
### Description

I have a problem with LuckPerms reading mysql database. Also, according to luckperms wiki with mysql issues, everything should be working. MySQL connection limit is also enough as all luckperms instances own fifth of whole limit. I can't join server because of that error and I need it to work

### Reproduction Steps

Will not be possible for you so I will tell how I made it:
-Installed bungee on my whole network (also in bungeecord plugins itself)
-Changes server names to correct ones
-Set storage system to MySQL and paste all data needed

Also maybe worth noting that:
1. My bungee and hub is hosted on hosting, survival server connected to bungee is hosted on VPS
2. Other plugins that need to use MySQL are working without any issue on the same database

### Expected Behaviour

I expect MySQL to work so i can normally configurate bungee permissions

### Server Details

Paper version git-Paper-790 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### LuckPerms Version

BG: 5.3.75 HUB: 5.3.74 SV: 5.3.47

### Logs and Configs

https://paste.gg/p/anonymous/c8e3a8df4bb04501a79a42814ec25f66

### Extra Details

As in description, I have checked wiki and every step is correct in my situation. No idea what could be wrong. Also I know that you may not have much time to check, answer etc. but please help ASAP cuz I need it as soon as possible :f

**Comment by Laarryy** [comment]
This particular 'failure to connect' error is caused by `javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)` 

If you don't want to use SSL, set `useSSL` in the config to false. 

Also, you mentioned that you installed "bungee" on all the servers - if you want to use LP properly, you install LP-Bungee only on the proxy (bungee, waterfall, etc) and then you install LP-Bukkit on each backend. *Then* you connect each server to the same database. 

Hope this solves your issue - please let me know if it does!

**Comment by xR4Z3R** [comment]
Yes it did work, thank you so much mate :D
