### ISSUE TITLE
/editor Bug

### ISSUE THREAD

**Issue by Hamsterliebe** [LuckPerms/LuckPerms#3261]
### Description

I try to go in the Web Editor and i noticed, that no Chat Message came... Both Console and Client.

Console Output had a lot of Errors (Warnings) and simply refused to work with me...

I have this on: 1 BungeeCord, 4 Subservers

No way to fix that?
The Version don't matter, because it is broken since a Month (and maybe even Longer) and it even broke on my Backups that are 1 year old....

### Reproduction Steps

Simply type in the Editor Command and have it connected to a Database

### Expected Behaviour

The Web Editor should open...

### Server Details

Paper 1.17.1 and 1.18

### LuckPerms Version

v5.3.94

### Logs and Configs

https://paste.lucko.me/8ZKSBmBBPQ

### Extra Details

If you have a Solution for me, write me a Message on Discord pleas! @|єɠєภ๔คгץ Hamsterliebe#0022

**Comment by Laarryy** [comment]
It appears something may be wrong with the actual permissions data you're sending to the editor - if you spin up a testing server with no saved permissions, does the editor work as intended?

Either that or your LuckPerms version is very very old, and you've somehow listed the wrong version here. Either way, try giving it a shot on a testing server.

**Comment by Hamsterliebe** [comment]
I have the newest Version (i done /ver LuckPerms) and the Test Server has the same Issue.. No Permission, no nothing but a not working Editor.. Bug stays the same in all Versions i tested (from very Old, 1 year ago to today downloadet and tested)

**Comment by Tobi406** [comment]
it looks like your tracks data is (partially) corrupted. Meaning your group list of a track/multiple tracks is not a list, which therefore cannot be read and gives the error.
The same bug should also occur when doing `/lp sync` since its trying to read the corrupted data there aswell. It therefore isn't a bug specific to the editor, but to everything that wants to read tracks, which also includes the `/lp listtracks` command.
Normally, your tracks data may look like this: 
![image](https://user-images.githubusercontent.com/43016900/148567258-3aa151dd-76a7-48d4-ad91-1769b4bf7173.png)

Which is completly valid JSON. Though if you remove the `["` to one groups entry (eg. we do this to the players groups) it is no longer valid:
![image](https://user-images.githubusercontent.com/43016900/148567589-751346d9-bc40-4422-9323-d2cc949ae833.png)

This is the exact error you have.
You also can NOT delete the track by doing `/lp deletetrack <track>`. Therefore the only way I think exists is manually editing your data and removing the error, or just scrap the `luckperms_tracks` table and therefore delete all tracks.

**Comment by Hamsterliebe** [comment]
Turned out, that the Database was brocken.. I made a new one, Imported the Files and everything worked fine! No Errors at all...
Weird Bug... At least its Fixed now
