### ISSUE TITLE
Allow setting player.getDisplayName() with luckperms

### ISSUE THREAD

**Issue by DevJoey** [LuckPerms/LuckPerms#3269]
### Description

It would be nice if i can set the displayname of a user with luckperms like /lp group admin meta setuserdisplayname "&4%name%" so that player.getDisplayname() will output that.

The same for users /lp user foobar meta setuserdisplayname "&4%name%"

### Proposed Behaviour

I have explained it above

**Comment by Laarryy** [comment]
Marking this out-of-scope because LuckPerms is not a display or chat plugin - it serves primarily as a permissions system. If you'd like, with your own code you could search LP meta for something like `meta.myserverdisplayname.DISPLAYNAMEHERE` and set it in your own code - this would be more along the lines of what purpose LP intends to serve. Additionally, if we were to start adding things like displayname, things like nicknames and other certainly-out-of-scope functions would rationally follow.
