### ISSUE TITLE
Copy command from editor with `--force` suffix if `[shift]` is pressed

### ISSUE THREAD

**Issue by molor** [LuckPerms/LuckPerms#3274]
### Description

Hello. We use LP on 4 servers with same permissions, but different players, and every time we changed something, we need to sync the changes between every server by performing `lp applyedits ... --force`. To be honest, it gets boring to add `--force` suffix every time.

### Proposed Behaviour

Make it so that when I click on the apply command using [shift] or [ctrl] it copies with "--force" already, this would be very convenient for us.

### Extra Details

Thanks

**Comment by lucko** [comment]
> We use LP on 4 servers with same permissions, but different players

This is not a supported usecase.

The *only* supported way to sync LuckPerms data between servers is to connect them all to the same database (most people pick MySQL).
https://luckperms.net/wiki/Network-Installation#installing-luckperms-across-your-network
https://luckperms.net/wiki/Syncing-data-between-servers

If you want to have your group permissions the same, but apply player permissions per-server, then you should use the server context. https://luckperms.net/wiki/Context

I'm very reluctant to add anything to make it "easier" to use the force flag, because frankly there is no good reason to do so. Hopefully you understand where I'm coming from?
