### ISSUE TITLE
Possible Plugin Conflict causing plugins to crash as well as the server

### ISSUE THREAD

**Issue by cj1705** [LuckPerms/LuckPerms#3317]
### Description

Basically after about 12 hours of the server running, the Spectator plugin starts throwing exceptions and in the thread dump it show luckperms could be part of it. This started happening after I updated LP to fix the editor issue. Also , in the end the server ended up crashing with luck perms in the paper thread dump. I've also contacted VentureChat and Spectator since they were also included.

### Reproduction Steps

Not too sure. 

It just started happening randomly. 

### Expected Behaviour

If it ends up being LP then. LP shouldn't be crashing other plugins. 

I have no idea what else to put here

### Server Details

git-Paper-408 (MC: 1.17.1)

### LuckPerms Version

v5.3.104

### Logs and Configs

https://gist.github.com/cj1705/06bf0b2c63a59f6d57c1ef6ab968b592

**Comment by lucko** [comment]
Looks like the issue could be caused by a deadlocked context calculator - a full thread stack dump (showing all threads, not just the server one) would be the best way to figure out what the problem is.

You can follow the steps here to generate one (when the server is timed out) https://gist.github.com/lucko/81033b72927eee0246dc8e8c284664c4

**Comment by cj1705** [comment]
Ill give it a shot if it pops up again. Thanks!
