### ISSUE TITLE
Data not being loaded. Please help ASAP as server is down

### ISSUE THREAD

**Issue by Nash738850** [LuckPerms/LuckPerms#3351]
### Description

Hello,

Someone on our server removed all the groups and all permissions. I was able to find a web editor from yesterday but when I load it the data won’t load I’m not able to get it back and I really need the info. Please help me get this back. 

### Reproduction Steps

Delete all data then try to load a backups after your restart the server and remove the file. 

### Expected Behaviour

Should load the groups and lermission

### Server Details

Paper 1.12.2

### LuckPerms Version

5.3.89

### Extra Details

Here is the link to the editor. 

https://luckperms.net/editor/I7ItebUq8e

**Comment by ZeromaniacMc** [comment]
Hi there,

first of all, I'm sorry to hear such thing happened to you. Seeing as this issue was opened 2 weeks ago, I am guessing you either found a solution or remade your setup. In case you seek an explanation as to why what you did didn't work:

The 'old' editor saves changes, not whole setups, meaning stuff that has a green or yellow-ish background in the editor. 
This is one of the reason why it's not advised to reuse the same editor and run applyedits multiple times, as changes made before will disappear. It sounds senseless at first glance, but if you remember that web editor data has to temporarily be stored somewhere and that service doesn't fall off of trees, it makes sense to minimize this load by only saving changes and not everything.
So what I believe happened was you tried to run applyedits on your game, which did not work because the editor did not contain 'edits'. 
In case something like that happens again, here's a way you can 'hack' this behavior: You can run the import command instead and use the 10-digit code which is part of your editor url as long as the editor is still valid (expires after 7 days).
In your case that would look like this: `/lp import I7ItebUq8e --upload`

I hope this explanation makes sense to you. Also, for a faster response, please consider visiting the discord first.
~cheers!
