### ISSUE TITLE
Update to 1.18.2

### ISSUE THREAD

**Issue by tskopen** [LuckPerms/LuckPerms#3354]
### Description

i updated to 1.18.2 and it kicks me when I join cause of luckperms. and causes some commands like /plugins not to work.

26.03 15:22:46 [Server] ERROR [LuckPerms] Exception occurred whilst loading data for e6599adc-72a3-493e-8235-3a102c8ae064 - tskopen
26.03 15:22:46 [Server] INFO java.lang.IllegalStateException: zip file closed
26.03 15:22:46 [Server] INFO at java.util.zip.ZipFile.ensureOpen(ZipFile.java:829) ~[?:?]
26.03 15:22:46 [Server] INFO at java.util.zip.ZipFile.getEntry(ZipFile.java:328) ~[?:?]
26.03 15:22:46 [Server] INFO at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
26.03 15:22:46 [Server] INFO at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]... (10 KB left)

and it kicks me cause of it

### Reproduction Steps

update to 1.18.2 paper and use luckperms I guess and try and join.

### Expected Behaviour

doesn't let people connect it just says "failed to connect"

### Server Details

paper-1.18.jar, MC 1.18.2

### LuckPerms Version

5.4.14

### Logs and Configs

https://mcpaste.io/9dd7e37188ea54aa

**Comment by ZeromaniacMc** [comment]
Hello,
came accross this and was wondering if you could resorve the issue?

If not, have you tried re-downloading the jar and/or restarting your server?
Also, I managed to get 'Zip file closed' after issuing the command /reload and using plugman, so that is a potential culprit as well. I use LuckPerms on my 1.18.2 paper server successfully, so this is quite interesting.
Would be cool to hear from you.
~Cheers

**Comment by tskopen** [comment]
Sorry I already reverted to 1.16.5 as it broke about of my plugins. glad to know it works for you, maybe it means in the future it can work for me. it may not have worked cause I learned it was installed while the server was online so that's not the smartest thing to do though.

**Comment by Chris6ix** [comment]
@tskopen 
Did you update directly from 1.16.5 to 1.18.2?
If so, then this may be why some of your Stuff like Luckperms broke...you cannot skip versions while upgrading!
You MUST update your Server through every major version at least once (Update step by step) to reduce the risk of running into issues.
If you did that then try again updating your server, but first to 1.17.1, and then to 1.18.2 (Remember to also update your Java version for these) to see if that fixes your Issues...

If some of your plugins broke on 1.18, then it's probably a good idea to either contact the dev to update their plugins, or to replace them with an up-to-date alternative...it's not good to run such old and outdated builds...especially if its just because some random plugin isn't updated...

Cheers,
Chris6ix

**Comment by tskopen** [comment]
Oh, thanks so much for that info! i didn't know that was a thing (: ill be sure to try that out at some point. thanks for the tip. ill close the thread as I think I found my answer 👍

**Comment by Chris6ix** [comment]
No problem :)
Hope that it fixes your Issue!

**Comment by tskopen** [comment]
nope i updated version to version and reuploaded it and it is still broke ):
https://mcpaste.io/1203a04ca677ab51

also idk if this changes anything but some plugins are talking about tasks 
09.04 01:13:51 [Server] WARN [Vault] Plugin Vault v1.7.3-b131 generated an exception while executing task 140
09.04 01:13:53 [Server] WARN [VotingPlugin] Task #28 for VotingPlugin v6.8.3 generated an exception

what are tasks? are they just like operations.

**Comment by tskopen** [comment]
09.04 01:42:52 [Server] INFO UUID of player tskopen is e6599adc-72a3-493e-8235-3a102c8ae064
09.04 01:42:52 [Server]  Ignored advancement 'minecraft:recipes/misc/iron_ingot' in progress file ./world/advancements/e6599adc-72a3-493e-8235-3a102c8ae064.json - it doesn't exist anymore?
09.04 01:42:52 [Server]  Ignored advancement 'minecraft:recipes/misc/iron_ingot_from_blasting' in progress file ./world/advancements/e6599adc-72a3-493e-8235-3a102c8ae064.json - it doesn't exist anymore?
09.04 01:42:52 [Server]  Ignored advancement 'minecraft:recipes/misc/gold_ingot' in progress file ./world/advancements/e6599adc-72a3-493e-8235-3a102c8ae064.json - it doesn't exist anymore?
09.04 01:42:52 [Server]  Ignored advancement 'minecraft:recipes/misc/gold_ingot_from_blasting' in progress file ./world/advancements/e6599adc-72a3-493e-8235-3a102c8ae064.json - it doesn't exist anymore?
09.04 01:42:52 [Server]  Ignored advancement 'minecraft:recipes/redstone/redstone_from_blasting' in progress file ./world/advancements/e6599adc-72a3-493e-8235-3a102c8ae064.json - it doesn't exist anymore?
09.04 01:42:52 [Server]  Ignored advancement 'minecraft:recipes/redstone/redstone_from_smelting' in progress file ./world/advancements/e6599adc-72a3-493e-8235-3a102c8ae064.json - it doesn't exist anymore?
09.04 01:42:52 [Server]  Ignored advancement 'minecraft:recipes/decorations/slime_block' in progress file ./world/advancements/e6599adc-72a3-493e-8235-3a102c8ae064.json - it doesn't exist anymore?
09.04 01:42:52 [Server]  Ignored advancement 'minecraft:recipes/building_blocks/mossy_stone_bricks' in progress file ./world/advancements/e6599adc-72a3-493e-8235-3a102c8ae064.json - it doesn't exist anymore?
09.04 01:42:53 [Server] ERROR Tried to load unrecognized recipe: minecraft:gold_ingot removed now.
09.04 01:42:53 [Server] ERROR Tried to load unrecognized recipe: minecraft:mossy_stone_bricks removed now.
09.04 01:42:53 [Server] ERROR Tried to load unrecognized recipe: minecraft:redstone_from_smelting removed now.
09.04 01:42:53 [Server] ERROR Tried to load unrecognized recipe: minecraft:gold_ingot_from_blasting removed now.
09.04 01:42:53 [Server] ERROR Tried to load unrecognized recipe: minecraft:iron_ingot removed now.
09.04 01:42:53 [Server] ERROR Tried to load unrecognized recipe: minecraft:iron_ingot_from_blasting removed now.
09.04 01:42:53 [Server] ERROR Tried to load unrecognized recipe: minecraft:redstone_from_blasting removed now.
09.04 01:42:53 [Server] ERROR Tried to load unrecognized recipe: minecraft:mossy_stone_bricks removed now.
09.04 01:42:53 [Server] ERROR Tried to load unrecognized recipe: minecraft:gold_ingot_from_blasting removed now.
09.04 01:42:53 [Server] ERROR Tried to load unrecognized recipe: minecraft:redstone_from_blasting removed now.
09.04 01:42:53 [Server] ERROR Tried to load unrecognized recipe: minecraft:iron_ingot_from_blasting removed now.
what does this mean?

also the issue is vault and luckperms I removed them and I can join again so yeah. I don't know how you got lp to work. where did you download the plugin @Chris6ix

**Comment by Chris6ix** [comment]
@tskopen I always download LP directly from Lucko`s Website (https://luckperms.net/)

It's weird that Vault and LP cause you issues...i literally never had issues with them :/
Maybe you could try a clean re-install (Delete their data folder and then load them to generate completely fresh files) and then re-configure them?

I think that you can ignore that Error...it's just part of upgrading your Server, I guess ¯\_(ツ)_/¯ (It seems to remove stuff in the player's file that doesn't exist anymore)
I remember also having something like that once when I updated my server, but it hasn't appeared again since then...

If you still get that all the time you join, then maybe check your plugins or datapacks to see if there is one that registers recipes or something...and then see if it needs an update for 1.18.2

**Comment by tskopen** [comment]
Ok then, that will be annoying to reconfig but ill try

**Comment by tskopen** [comment]
nope i downloaded fresh copies that are more fresh then mints and it still broke /:

**Comment by Chris6ix** [comment]
What plugins do you have installed? 
Have you tried to load your LP files on a separate, clean 1.18.2 server without any other plugins and join it...if it's fine then it's some other plugin that is causing issues.
If It's still broke, then i really don't have any idea what else it could be as my LP is running perfectly fine on a 1.18.2 Paper...and i also never heard of this "zip file closed" error you`re getting :/

**Comment by ZeromaniacMc** [comment]
Honestly I see a major problem here with 'per world plugin loader'.
I just did some research since I'm rather curious and just know that 'zip file closed' is **not** an error specifically in luckperms, but rather exists in **all of java**. 
I suspect, after my research, that your per world plugin thing is trying to limit luckperms in some way so that it cannot operate properly, trying to handle the player login and literally being choked while trying - as it should. 
Try a clean an up-to-date paper jar and luckperms. Don't do 'per world plugins' - there's a reason why this isn't natively a thing in plugins. It would be helpful to see another log if you still get this with an up-to-date paper and luckperms installation without anything else. If it's fixed then, you know it's not luckperms for sure.

**Comment by emilyy-dev** [comment]
@ZeromaniacMc has a point, I wanted to add that PWP **is known** to break dozens of plugins. Do as Zero suggested and please report results back.

**Comment by Chris6ix** [comment]
Exactly that was also my suspicion...that's why I wanted him to try LP on a clean server...but I was not 100% sure because of the `**** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****` in the Error log...

**Comment by tskopen** [comment]
Its hard for me to do it on a clean server cause I use a paid hosting site but I think ik a way I can do it. PWP never caused me issues before and its vital for my server but ill try without it

**Comment by tskopen** [comment]
well shit, I guess it is PWP 

Only luckperms
https://mcpaste.io/fef2f0fd497c52c2

Vaullt and luckperms
https://mcpaste.io/9cbdb7b369e123ad

all but PWP
https://mcpaste.io/42559efa3095e838

So it works without PWP. Does anyone know any substitutes to PWP cause it's a vital plugin for my server?

this makes me realize how fast servers load without plugins

**Comment by ZeromaniacMc** [comment]
Any 'substitute' would, in the essence do the same thing. This is why people use multi-server networks instead of fiddling with per-world stuff. 
All I can recommend is to make use of the context system to allow/disallow commands/actions per world. If that is not enough for you then I'm afraid you're on your own.

**Comment by tskopen** [comment]
isnt PWP a context system?, i dunno maybe i can find a way to use LP
Thanks for the help I think I can go on now. ill reopen this if I find another road block related to lp or something

**Comment by ZeromaniacMc** [comment]
What I meant with context system was luckperms contexts: [here](https://luckperms.net/wiki/Context)

Maybe you csn picture whats happening better like this:
Once your server starts, it 'knocks on the door' of every plugin to which the plugins 'open up' or, well... plug in. What PWP does is quite literally shoving that door shut after the startup, not allowing lp to load data for you. Zip file closed could be reworded to 'Something chained me up inside, i can't do my job'. 

Using permission context is very different from smashing doors shut. Btw this is also why using plugman or /reload is a bad idea.

**Comment by tskopen** [comment]
ah ok that makes sense thanks for the explanation (:
