### ISSUE TITLE
Prefix for group doesn't show in chat

### ISSUE THREAD

**Issue by Aleberi** [LuckPerms/LuckPerms#3395]
### Description

If I try to add a prefix using "/lp group (group) meta addprefix" the command goes through and shows up in the luckperms editor but doesn't show up next to a person's name in chat.

![image](https://user-images.githubusercontent.com/107239609/173005618-8321c3dd-837a-41a3-9e16-16633526227a.png)

### Reproduction Steps

Add a prefix to group default called anything, with this command template /lp group default meta addprefix 2 "[person] " and have someone in that group send something through chat and you shouldn't be able to see the prefix to the left of the player's user.

### Expected Behaviour

I was expecting the prefix to show next to my user  "<[Members] (user)>"  but instead doesn't show in chat even though you can see the prefix in the permission nodes of the web editor.

### Server Details

CraftBukkit version 3508-Spigot-fa893f0-50ef122 (MC: 1.19)

### LuckPerms Version

v5.4.26

### Logs and Configs

https://gist.github.com/Aleberi/99d212402d1ac788188db245c685cc2d

**Comment by ZeromaniacMc** [comment]
Hello there!
As explained [here](https://luckperms.net/wiki/FAQ#why-are-prefixessuffixes-not-working), LuckPerms does not do any chat or tablist formatting whatsoever. LuckPerms will save the prefixes and suffixes which you can see in `/lp user <username> info` when the user is part of said group, however it will not forcefully inject them anywhere. 
You will need a chat plugin of your choice as well as vault since many chat plugins work with vault rather than hooking directly into LuckPerms. If you have Essentials already, which seems to be the case based on the red username, getting the chat addition EssentialsX Chat and Vault will fix this. To clarify this, chat or other plugins must ask LuckPerms for the prefix and/or suffix and they display it at the position which their config's format is set to. LP merely serves as a data storage for them, so what you're experiencing is not a bug/issue on LuckPerms' side.
Consider joining the [Discord](https://discord.gg/luckperms) if you need more help with LuckPerms, as usually response times are way better there than here on github.
~Cheers

**Comment by Aleberi** [comment]
Ohhhhh I see. Yes, I already have EssentialsX and Vault, but I hadn't added EssentialsX chat. As thought, EssentialsX Chat fixed the issue. Thanks for the help!
