### ISSUE TITLE
Argument based command permissions didn't work

### ISSUE THREAD

**Issue by Darkluke11** [LuckPerms/LuckPerms#3416]
### Description

I tried to setup an Arguement based command following : (luckperms.user.parent.add.admin) but the person dosent get the permissions to do /lp user <name> parent add admin i also activated the option in the config file if  i give the person luckperms.user.parent.add it works fine but also with every rang. So i think its a failure in the plugin.

### Reproduction Steps

install plugin, change the config.yml at argument-based-command-permissions to true, add person luckperms.user.parent.add.admin and try after save /lp user <name> parent add admin also try with another rang

### Expected Behaviour

the person can add some one the rang admin but not other rangs

### Server Details

MC : 1.18 Paper

### LuckPerms Version

v5.3.86

**Comment by ZeromaniacMc** [comment]
Hey there. I've just tried this myself. 
First of all, I figured out that enabling argument based command permissions requires a restart. Reloading the config will not work. The same thing applies to using plugman or /reload - it will break brigadier, which is responsible for letting you tab complete commands.
Secondly, I had the issue that plugin-hide-pro (because I did not whitelist the command) yeeted it for me. So if you have any plugin for command-whitelist, consider it could be that. 
Furthermore, it is not only one permission that is being checked. I used [verbose](https://luckperms.net/wiki/Verbose) to see what exactly is needed since the permissions are layered a lot. There is 'self', 'others', 'parent add', 'parent set' and also a node to use specific context or global (which is mentioned in the bottom most part of the wiki page). 
I got this to work with the following permissions added:

➢ luckperms.usecontext.global
➢ luckperms.user.parent.add
➢ luckperms.user.parent.add.admin
➢ luckperms.user.parent.add.modify.others

Hope this helps. 
~ Cheers.
