### ISSUE TITLE
prefix as a nickname

### ISSUE THREAD

**Issue by ViPEk213** [LuckPerms/LuckPerms#3448]
### Description

when i type 
![image](https://user-images.githubusercontent.com/110340203/182658835-263f3982-fbc9-485b-9b96-c3eec9d1b2a3.png)
it makes prefix as a nick i used plugin essentials
i didnt have this issue before i reload my server

### Reproduction Steps

1. say what i have to do

### Expected Behaviour

i expected to prefix dont show

### Server Details

Spigot 1.19

### LuckPerms Version

v5.4.30

**Comment by Aberdeener** [comment]
Hi there,

LuckPerms does not interact with the player name tab completion suggestions (or even setting player display names for that matter).
Some other plugin on your server is doing this - I suggest you start by eliminating any plugins that could set a player display name and seeing if the problem is solved then.

**Comment by ViPEk213** [comment]
hello,
the commands from EssentialsX do this but i dont want to delete this plugin
can you help me fix it?
