### ISSUE TITLE
Add auto-delete player from the database along with his donation if he did not go n time.

### ISSUE THREAD

**Issue by Regomy** [LuckPerms/LuckPerms#3475]
### Description

I propose to add a line in the config and a command with argument checking, like /lp purge time or /lp purge time group. This command should remove all players or players from a particular group who have not logged on the server for more than n time.

### Proposed Behaviour

In this case, it will help that the players who do not go more than n time will be removed from the base and not clog it.

### Extra Details

Everything is described above.

**Comment by LeotomasMC** [comment]
players with only the default group are not stored in the database. also removing *paid* ranks just because they havent joined in a certain amount of time seems really scummy imo. additionally, this wouldnt really work on a bungee/velocity network, because afaik luckperms does not keep track of the last time a player was connected to the server. im not sure the proxy keeps track of that either, and that would mean no single server knows the last time any individual player connected to the server.
im not really sure why you would even want to do this anyways. your database should not be taking up that much space, and if it is, i dont think players that havent joined in a while should be your biggest concern

**Comment by lucko** [comment]
Suggestion is out of scope for the main plugin, but you could achieve this with an add-on using the API.
