### ISSUE TITLE
Unable to set minecraft permissions to false

### ISSUE THREAD

**Issue by powercasgamer** [LuckPerms/LuckPerms#3616]
### Description

Can't negate minecraft command permissions

### Reproduction Steps

Whilst opped:

1. Try `/gamemode creative` (works)
2. do `/lp user <you> permission set minecraft.command.gamemode false`
3. Try `/gamemode creative` again. Works when it shouldn't

Doing `/lp verbose command me gamemode` says false as expected and also gives the no permission message
![javaw_4lKYSWWs9j](https://user-images.githubusercontent.com/40437205/229316432-19195039-d54c-45aa-b61c-0a4860bd82f9.png)

### Expected Behaviour

Actually negate minecraft permissions

### Server Details

git-Paper-484 (MC: 1.19.4) (Git: 7a96bf2)

### LuckPerms Version

v5.4.71

**Comment by lucko** [comment]
Seems like being opped causes the permission to not be checked, this is probably a Bukkit/Spigot/Paper issue

**Comment by Machine-Maker** [comment]
I think this can be solved by using the `ignore-vanilla-permissions` setting in `commands.yml` on craftbukkit/spigot/paper. This setting basically removes the "op level" check for permissions, so only the bukkit permissions is checked.

The issue is that an opped player has a permission level (1-4). When the game goes to check if a player can use a vanilla command, first the op level check is done. If that fails, the bukkit permission is checked. The above setting just makes the first op level check ignored.
