### ISSUE TITLE
release update to spigotmc

### ISSUE THREAD

**Issue by games4681** [LuckPerms/LuckPerms#3702]
### Description

You haven't issued an update to luckperms on your spigotmc page for six months. I suggest here that you issue an update to spigotmc because not everyone knows how to go directly to your website and are still using a very old version and a bit unpleasant from them in my opinion.

### Proposed Behaviour

here is the spigotmc of luckperms: https://www.spigotmc.org/resources/luckperms.28140/
version: 5.4.40
and luckperms now: 5.4.98
here is the luckperms website: https://luckperms.net/

**Comment by games4681** [comment]
I am closing because there was no response for two weeks, this means that the programmers are not active here and probably would not have responded if I had left it open.
It's a shame that there are programmers who give space to ask for requests or complain about faults but don't really come to provide the promised support, it would be better if you didn't open your own github and you would save us the time to just write things.

**Comment by Turbotailz** [comment]
I couldn't help but comment here. You're attitude in this issue comes across as very entitled and you should probably adjust your expectations when it comes to dealing with open source software maintainers.

Firstly, it is not necessary to continuously update the plugin on Spigot or other websites, LuckPerms is pretty stable with most versions so there's not really much that people are missing out on by running an older version. 

Secondly, Luck is the sole developer of the LuckPerms plugin and has a life outside of developing open source software which he does in his spare time. It takes a lot of time to release the plugin to the various sites that it is hosted on. Some of these have an API which makes releasing easier but in the case of SpigotMC, it has to be done manually. You can see how a plugin that often updates might slip a bit behind on being uploaded to the platform.

Thirdly, three weeks isn't really that much time for an issue to be open without any response. Keeping this open would have been a good reminder for Luck to add a new release, when he eventually makes time to check the open issues (which he does every now and then, usually in bulk). Sorry you felt the need to close it because it wasn't acted on quick enough... you should see how long tickets stay open at my company!

Fourthly, and this one will seem the most harsh, but no one is "promised support" here. Luck is not obligated to support anyone with his plugin. You are not entitled to support simply because a Github issues section is enabled. Anyone providing support to open source software, does so without any form of compensation. You are not a customer with rights. We owe nothing to you.

Looking through your issue history, it seems like you have a habit of opening issues and then closing them because of no response (usually within a day or week of submitting). Maybe stop that and let the developers get to the issue when they can :)
