### ISSUE TITLE
Spigot 1.20.1 server crashed with luckperms

### ISSUE THREAD

**Issue by Doushabao233** [LuckPerms/LuckPerms#3741]
### Description

I'm using LuckPerms on my spigot 1.20.1 server and it crashes about every half hour.
The log says the error is from LuckPerms.

### Reproduction Steps

This is all the plugins i installed.
LiteItemShow, WorldEdit, ChatImage, ScreenInMC, Boom, fakeplayer, GSit, ViaVersion, HuskHomes, floodgate, InvSeePlusPlus, QuickLogin, ViaBackwards, CoreProtect, SkinsRestorer, Geyser-Spigot

From the crash log, I see "MySQL". So it might be a database problem, I'll give the database here too.

[Database.zip](https://github.com/LuckPerms/LuckPerms/files/12426346/Database.zip)

### Expected Behaviour

It shouldn't crash.

### Server Details

LuckPerms-Bukkit-5.4.102.jar, This server is running CraftBukkit version 3857-Spigot-94e187b-8ef7afe (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### LuckPerms Version

v5.4.102

### Logs and Configs

https://gist.github.com/Doushabao233/4b4a986301c57f49dd1144733a7c94ce

**Comment by underscore11code** [comment]
Nope, this crash is not caused by LP. When watchdog kills the server, it prints every running thread; LuckPerms is running several threads, hence it's appearance several times. Database connections also usually maintain several threads, hence MySQL appearing a bunch. The thread you care about is the first one, `Server Thread`. Looks like something to do with world generation or loading.

**Comment by Doushabao233** [comment]
> Nope, this crash is not caused by LP. When watchdog kills the server, it prints every running thread; LuckPerms is running several threads, hence it's appearance several times. Database connections also usually maintain several threads, hence MySQL appearing a bunch. The thread you care about is the first one, `Server Thread`. Looks like something to do with world generation or loading.

Thanks.
