### ISSUE TITLE
Keep old releases of LuckyPerms

### ISSUE THREAD

**Issue by tosum** [LuckPerms/LuckPerms#3742]
### Description

Download links for old versions stop working after a while.

For example here's a link to `LuckPerms 5.4.17`:
https://download.luckperms.net/1483/fabric/LuckPerms-Fabric-5.4.71.jar
Trying to download this file results in `404 Not found`.

This is a bit annoying. We have a script which downloads the plugin and sets up the server, but it stopped working when the link started throwing 404.

### Proposed Behaviour

Would it be possible to keep old versions of `LuckyPerms` around? Each release is only 1.5 MiB, so it shouldn't take up that much space (and it could be hosted on github, like https://github.com/LuckPerms/LuckPerms/issues/3358 suggests).

We really enjoy using `LuckyPerms`, but we have to host our own web server just to be able to download an old version of the plugin, which really feels overkill.

Thank you!

**Comment by LeotomasMC** [comment]
old fabric and forge releases can be found on [Modrinth](https://modrinth.com/mod/luckperms/versions#all-versions) or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/luckperms/files). The reason old versions are not saved on download.luckperms.net is because that is basically an alias for the Jenkins CI that actually builds each release of LuckPerms and that doesnt keep old builds

also the latest release is actually ~13mb because it has separate jars for 8 platforms, and since there have been 1500 builds, that would've added up to about 20gb (ignoring the fact that platforms have been added over time).

**Comment by tosum** [comment]
> old fabric and forge releases can be found on [Modrinth](https://modrinth.com/mod/luckperms/versions#all-versions) or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/luckperms/files).

Thank you that's really useful. We changed our download link to download the package from CurseForge, hopefully it doesn't break.

I guess it solves my immediate issue, but I still think that it would be nice if the official links didn't break. But feel free to close this issue if you're against the idea.
