### ISSUE TITLE
Fake UUID

### ISSUE THREAD

**Issue by hiiamken** [LuckPerms/LuckPerms#3805]
### Description

I'm having a situation where I ban a player's IP (essential) but they can still access the server with a different UUID but the name is still the same.

### Reproduction Steps

- Banip player
- He changes his UUID (idk how)
- Ho can connect my server after that

### Expected Behaviour

I see that after fake UUID times, luckerperm will notify the console

### Server Details

Paper 1.20.1

### LuckPerms Version

lastest

### Logs and Configs

https://mclo.gs/iDqRcCc

**Comment by ImDarkLaw** [comment]
This is clearly **not** a LuckPerms issue, but rather your server running in **offline mode** and not properly authenticating players. Such behavior is expected on an offline mode server. Consider enabling online mode in your __server.properties__ file or follow the suggested [network installation setup](https://luckperms.net/wiki/Network-Installation#pre-setup) if you're on a network.

**Comment by ImDarkLaw** [comment]
No. LuckPerms on the proxy side won't automatically sync permissions or replace LuckPerms on your backend servers. 

Since you're, longer, on a network we suggest you check the [Switching storage types](https://luckperms.net/wiki/Switching-storage-types>) guide on how to properly migrate your permissions and groups and you follow the [Network Installation](https://luckperms.net/wiki/Network-Installation) guide to sync LP data across your whole network. 

Be sure to take a [backup](https://luckperms.net/wiki/Switching-storage-types#backups) before changing your storage type and/or migrating your LP data.
