### ISSUE TITLE
Large console error

### ISSUE THREAD

**Issue by DoZysGuy** [LuckPerms/LuckPerms#3815]
### Description

There is an large console error that appear sometimes after I install ExtraContext and add a placeholdercontext

### Reproduction Steps

1 Install ExtraContext
2 Add a placeholder context
3 Add a permission with this context

### Expected Behaviour

I really don't know because all is working but this error appear sometimes

### Server Details

Mohist 1.20.2-131

### LuckPerms Version

v5.4.102

### Logs and Configs

Here the config of extracontext and the console error
https://gist.github.com/DoZysGuy/f75cb59783fa0bbaf1559c3096a219c6

**Comment by emilyy-dev** [comment]
(Most) LP placeholders cannot be used in contexts, why that is is because, for example, permission `abc` has as context `%luckperms_check_permission_xyz%`, and that placeholder needs to be resolved, the plugin needs to check whether `xyz` applies, and to check whether a permission applies or not the contexts need to be resolved, which requires the placeholder to be resolved which requires to check the permission .... and it is caught in an endless loop (until this error happens).

The suggested alternative for this is to just use a group, e.g. `xyz` and in that group add the permission `abc` and all the other permissions that would apply if `xyz` existed as well (so when you have the group xyz you have all the permissions under it).

For further support please use the discord server.
