### ISSUE TITLE
Data too long for column 'permission' at row 1

### ISSUE THREAD

**Issue by stormkiller0** [LuckPerms/LuckPerms#3856]
### Description

Data too long for column 'permission' at row 1

my permission: essentials.{spawn,home,sethome,delhome,balance,balancetop,msg,msgtoggle,rtoggle,mail,mail.send,ignore,tpa,tpaccept,tpacancel,tptoggle,pay,paytoggle,motd,warp,warp.list,kit,kits.start,sethome.multiple.default}

### Proposed Behaviour

1

**Comment by stormkiller0** [comment]
increase the limit in the scheme sql

**Comment by underscore11code** [comment]
Permissions are hard capped to `200` characters. While the shorthand permissions can be convenient, unless it's a case where the shorthand part is in the middle (i.e. `foo.{a,b}.bar`), it's usually better to just enter each permission individually.

**Comment by underscore11code** [comment]
If there's a legitimate reason to raise the hard cap, please let us know, otherwise this is working as intended.

**Comment by stormkiller0** [comment]
@underscore11code  Some permissions are very long, so you can change the limits to 250 characters

**Comment by underscore11code** [comment]
I've been doing this for almost 4 years now, and the only times I've ever seen the limit be an issues is either a) cases like this where shorthand or regex permissions are being abused, or b) prefixes/suffixes with hex code gradients with a 14 character RGB format (i.e. spigot's `&x&R&R&G&G&B&B`).

If you can provide a real-world example of a public plugin that utilizes 200+ character permissions, provide it here, and we might consider raising the limit if/when v6 happens. Otherwise, this is working as intended.
