### ISSUE TITLE
Faild MySQL connection

### ISSUE THREAD

**Issue by realTheWise** [LuckPerms/LuckPerms#3982]
### Description

When I start my server (paper-1.21.1-119), LuckPerms does not connect to my MySQL database.

The log is attached below.

I have set the config correctly.

### Reproduction Steps

I have configured MySQL (see config.yml) and started my server.

The database is created correctly and the user has access to it.

[config.txt](https://github.com/user-attachments/files/17332738/config.txt)

_(I uploaded the config as txt because GitHub does not support yml files.)_

### Expected Behaviour

I just wanted it to work.

### Server Details

paper-1.21.1-119

### LuckPerms Version

LuckPerms-Bukkit-5.4.141

### Logs and Configs

[latest.log](https://github.com/user-attachments/files/17332674/latest.log)

**Comment by BNTFryingPan** [comment]
either the address is incorrect (either a typo, or you need to use a different address because you are in a containerized environment), or something is blocking the connection

in the future, upload text files as a [github gist](https://gist.github.com] so that they dont need to be downloaded to be viewed (and it supports yaml)

**Comment by realTheWise** [comment]
@BNTFryingPan I was able to solve the problem. It is due to an error on my MySQL server. Thanks anyway!
